### ISSUE TITLE
UTF Support

### ISSUE THREAD

**Issue by 6xingyv** [nearby-sharing/android#102]
For those whose phone's named in other languages, theirs device's name will be wrongly displayed.

Example:
Orginal device name: 阿睿的Xiaomi 13
Displayed device name:
![image](https://github.com/nearby-sharing/android/assets/47916764/948d740c-ddb2-4d1e-9389-3ccb8958efa4)

**Comment by ShortDevelopment** [comment]
Hey, could you please test how the app behaves if you remove a single Chinese letter from the device name?

**Comment by 6xingyv** [comment]
> Hey, could you please test how the app behaves if you remove a single Chinese letter from the device name?

Yes, i change it to 睿的Xiaomi 13
![image](https://github.com/nearby-sharing/android/assets/47916764/17bb853a-06e0-4c9f-aa5d-0f34d63fe94a)

**Comment by ShortDevelopment** [comment]
After long investigations, it seems like this is a display bug in windows.
Could you maybe create a ticket in the feedback hub for that?

(Feel free to come back to this if I'm wrong)
