### ISSUE TITLE
Unauthorized Access Exception

### ISSUE THREAD

**Issue by fralk** [nearby-sharing/android#124]
Huawei Mate 10 Pro (android 10) I'm unable to receive any file from windows 10, seems like permissions for storage is denied even though I granted them

![Screenshot_20231210_191126](https://github.com/nearby-sharing/android/assets/92763850/af429262-65f9-448e-a9f3-93e50c24c0a1)
![Screenshot_20231210_191246_com google android permissioncontroller_edit_24563807648855](https://github.com/nearby-sharing/android/assets/92763850/287b93ba-d66c-4ac3-b20b-47c077ca8361)

**Comment by saadati944** [comment]
I have this exact problem on a xiaomi device with android 10

**Comment by ShortDevelopment** [comment]
@fralk Have you created a file with the same name before?

**Comment by fralk** [comment]
> @fralk Have you created a file with the same name before?

nope; have tried with different files, all the same

**Comment by ShortDevelopment** [comment]
Okay, I'm going to let the app cache the received file first and then copy to Downloads using Androids Storage Framework.

**Comment by iGameEveryDay6** [comment]
I'm facing this issue as well. I'm running the app on a Huawei P20 Pro on Android 10.

**Comment by bohaoy** [comment]
I'm also facing this issue on the Huawei MatePad Pro 10.8 (2019) running Android 10. For me regardless of what device is sending the file, the exception occurs.

It does seem like it's related to Huawei devices though

**Comment by ShortDevelopment** [comment]
I'll try to fix this bug this week
