### ISSUE TITLE
Windows 10 not detecting phone

### ISSUE THREAD

**Issue by NicTech-1989** [nearby-sharing/android#126]
Phone to PC works perfectly
But PC to phone is not working
Windows 10 just keep telling you looking for nearby devices and the mobile device does not come up.
![17039406659888168082546519760293](https://github.com/nearby-sharing/android/assets/74213698/351c89cb-7663-47f9-b6f0-e240c740f65e)

**Comment by ShortDevelopment** [comment]
@NicTech-1989 Have you enabled allow to receive from everyone on your PC?

**Comment by NicTech-1989** [comment]
> @NicTech-1989 Have you enabled allow to receive from everyone on your PC?

Yes i have. Receive from anyone and send to anyone

**Comment by ShortDevelopment** [comment]
Could you please
 - enable logging on your PC (https://nearshare.shortdev.de/protocol/logging/)
 - let your phone advertise itself
 - send me a PM with the logs via mail: nearshare@shortdev.de

**Comment by NicTech-1989** [comment]
> Could you please
> 
> * enable logging on your PC (https://nearshare.shortdev.de/protocol/logging/)
> * let your phone advertise itself
> * send me a PM with the logs via mail: [nearshare@shortdev.de](mailto:nearshare@shortdev.de)

Ok will do when i get back home.
PS. Im using a Honor X6 Android 12
And Both my Laptop and Phone Are Connected to the same wifi network.

**Comment by NicTech-1989** [comment]
> Could you please
> 
> * enable logging on your PC (https://nearshare.shortdev.de/protocol/logging/)
> * let your phone advertise itself
> * send me a PM with the logs via mail: [nearshare@shortdev.de](mailto:nearshare@shortdev.de)

how do I go about setting up logging. I'm a beginner at this stuff. Please advise me thanks

**Comment by NicTech-1989** [comment]
> > Could you please
> > 
> > * enable logging on your PC (https://nearshare.shortdev.de/protocol/logging/)
> > * let your phone advertise itself
> > * send me a PM with the logs via mail: [nearshare@shortdev.de](mailto:nearshare@shortdev.de)
> 
> how do I go about setting up logging. I'm a beginner at this stuff. Please advise me thanks

i did my best in making the logs. i hope i did it correctly. i sent them to you.

**Comment by ShortDevelopment** [comment]
Hey, thanks; Seems like you sent me the right files and bluetooth is enabled!

How long did you wait before you collected the logs from `C:\Windows\ServiceProfiles\LocalService\AppData\Local\ConnectedDevicesPlatform`?
All messages are from within a single second...

**Comment by NicTech-1989** [comment]
what about now

**Comment by ShortDevelopment** [comment]
You could test with different Windows and Android devices if possible.
That could help in isolating the issue.

**Comment by ShortDevelopment** [comment]
I'm closing this as I don't have enough information / ideas to investigate this further.
Feel free to comment with further information.

**Comment by fxzxmicah** [comment]
I have the same problem with Windows 11 and can't discover my phone on my PC.

**Comment by ShortDevelopment** [comment]
@fxzxmicah 
Do you see it on another PC / Phone?

**Comment by ShortDevelopment** [comment]
If your phone is connected via bluetooth, please try to disconnect or even unpair and try again.

**Comment by fxzxmicah** [comment]
After repairing, it worked normally. If I don't pair them, the receive notification doesn't appear on my phone.
