### ISSUE TITLE
Quick qs tile doesn't work

### ISSUE THREAD

**Issue by abdulkarimx1** [nearby-sharing/android#128]
The quick qs tile doesn't do anything when clicked, although it's labeled as ( receive ) so i think it have to do something or maybe accept the incoming files ?

**Comment by matroosoft** [comment]
It works here.. Android 8 on LG V30

**Comment by abdulkarimx1** [comment]
> It works here.. Android 8 on LG V30

Android 8 ? Google now has android 14 my friend, i forgot to mention I'm using A14.

**Comment by matroosoft** [comment]
Sorry. Android 9 I'm at.

**Comment by matroosoft** [comment]
Just to be clear, I'm not the developer, just another user of the app.

**Comment by ShortDevelopment** [comment]
The quick settings tile should currently only opens the receive Activity as @matroosoft pointed out.

Strange if that doesn't work. 
I'll need to test with an emulator, as I'm still on Android 12.

This will change once I got the background service (#41) in place.

**Comment by ShortDevelopment** [comment]
Closing as duplicate of #41
