### ISSUE TITLE
Receive tile in the control centre does not work on HyperOS

### ISSUE THREAD

**Issue by Vader77Darth** [nearby-sharing/android#133]
Tapping it crashes nearby sharing. Long pressing on it also causes nearby sharing to crash. I can only get this issue to happen on HyperOS.
I have attached a screen recording of the issue and a screenshot of the log that HyperOS gave me.

[Screenshot_2024-02-04-21-13-24-457_com miui bugreport](https://github.com/nearby-sharing/android/assets/87441738/5ebe50b8-d55b-46de-906b-34245bd48e9e)

https://github.com/nearby-sharing/android/assets/87441738/67f009a8-8820-43e1-a603-12764ea44ad6

**Comment by ShortDevelopment** [comment]
Interesting ... all theses Chinese brands seem to have their own rules 😅
I'll revisit this when I'm doing #41

**Comment by Vader77Darth** [comment]
Yea. I guess #41 is the ultimate solution.

**Comment by ShortDevelopment** [comment]
This was likely fixed in 5bd63bfd32760b6d80584636f2466595cb4d4b34
https://github.com/nearby-sharing/android/blob/5bd63bfd32760b6d80584636f2466595cb4d4b34/src/QuickSettings/ReceiveTileService.cs#L16-L21
