### ISSUE TITLE
Nearby Share (Now Quick Share) is extremely slow from Android to PC

### ISSUE THREAD

**Issue by mishrasubhajit** [nearby-sharing/android#135]
Hi,

The slow speed problem for sending files from Android to PC remains, even if Nearby Share is now Quick Share. For example, the transfer speed doesn't exceed 2.5kb/s (on average) while sending a jpeg file of around 150kb. It takes more than 10 min to send a 4 MB file to a PC. A screen recording has been attached.

I had mentioned this problem previously. I hope there is some kind of fix to the slow speed. I am sure it is not an issue of Wifi or Bluetooth connection. The speed is quite fast in the other direction.

Thank you.

https://github.com/nearby-sharing/android/assets/13003528/b4da2975-a7d0-4969-8384-9853c2e6f44a

**Comment by matroosoft** [comment]
I experienced this a few times too.

**Comment by ShortDevelopment** [comment]
@mishrasubhajit Quick Share is a totally different app 😅

https://nearshare.shortdev.de/docs/download
