### ISSUE TITLE
Failed to transfer files from Android 14 phone to computer

### ISSUE THREAD

**Issue by AnnualfireCHW** [nearby-sharing/android#166]
![屏幕截图 2024-05-07 112200](https://github.com/nearby-sharing/android/assets/121853113/0cd49c25-e88b-4248-9ac3-c62e31d967f3)

**Comment by AnnualfireCHW** [comment]
如果开发者需要，我可以尝试提供更多有效信息。

**Comment by ShortDevelopment** [comment]
Hi, I've got some questions for you 🙃
- Could you please communicate in English?
- What version of the android app are you using?
- Does that happen... 
  - every time?
  - with every device?
  - with every file?

**Comment by AnnualfireCHW** [comment]
> Hi, I've got some questions for you 🙃
> - Could you please communicate in English?
> - What version of the android app are you using?
> - Does that happen... 
>   - every time?
>   - with every device?
>   - with every file? 

你好:）看起来你使用英语，我将使用翻译器来进行这一对话，如果发现了不正常的对话，请多包涵，因为这可能是翻译器的问题

Hello :) looks like you're using English, I'm going to use a translator for this conversation, if you find something that isn't working, please bear with me because it might be a problem with the translator

**Comment by AnnualfireCHW** [comment]
> Hi, I've got some questions for you 🙃
> - Could you please communicate in English?
> - What version of the android app are you using?
> - Does that happen... 
>   - every time?
>   - with every device?
>   - with every file? 

Android版本为14，应用程序版本1.74 1.73 1.72   
上述版本均尝试过，至少我手中的两台设备都有类似问题，我首先试了700MB的压缩包，发现无法传送，再试试几KB的音频文件等，均不好用。我甚至还换了原生安卓资源管理器传送文件到电脑，但仍然不行
但奇怪的是电脑上的文件可以传送到手机上，而且稳定性比之前高。

Android version 14 and app version 1.74 1.73 1.72   
I've tried all of the above, at least the two devices I have have similar problems, I first tried the 700MB compressed package, and found that it couldn't be transferred, and then tried a few KB of audio files, etc., all of which didn't work. I even switched to the native Android explorer to transfer files to my computer, but it still didn't work
But the strange thing is that the files on the computer can be transferred to the phone, and the stability is higher than before.

**Comment by AnnualfireCHW** [comment]
发现这种问题大概是windows更新前后，我将使用另一台未更新的电脑设备看看共享是否好用
I found this problem probably before and after the Windows update, and I will use another computer device that is not updated to see if the sharing works

**Comment by ShortDevelopment** [comment]
@AnnualfireCHW Thanks for the clarification!
Could you please send me the log files from your phone via mail (nearshare@shortdev.de)?
https://nearshare.shortdev.de/technical/logging/

**Comment by AnnualfireCHW** [comment]
> @AnnualfireCHW Thanks for the clarification!
> Could you please send me the log files?
> https://nearshare.shortdev.de/technical/logging/

OK

**Comment by AnnualfireCHW** [comment]
有些尴尬的是，当我再次尝试复现问题时，可以进行正常传输，这真的非常尴尬，可能因为我今天重新安装了windows，再次尝试安装最新版本（Windows版本和Android的程序版本都为最新）复现问题，但奇怪的是问题不知不觉中被修好了，很抱歉我给出了没有用的参考，另外你所说的日志路径我已经查找，并没有相关的文件，我没有办法提供日志
It's a little embarrassing that when I try to reproduce the problem again, I can do a normal transfer, which is really embarrassing, probably because I reinstalled windows today, tried to install the latest version again (both the Windows version and the Android program version are the latest) to reproduce the problem, but the strange thing is that the problem was fixed unknowingly, sorry I gave a useless reference, in addition I have looked up the log path you said, and there are no related files, I have no way to provide the logs

**Comment by ShortDevelopment** [comment]
No problem, I'm glad your issue is resolved. 😊
If you encounter similar behavior in the future, just reopen this issue!

Your file-manager may hide the `Android` folder.
On my Samsung phone, I can enable to show all files via a dropdown at the top of the screen.
