### ISSUE TITLE
"Enable Bluetooth" crashes when missing permission `BLUETOOTH_CONNECT`

### ISSUE THREAD

**Issue by HumanMus1c** [nearby-sharing/android#174]
Crash after click "Enable Bluetooth" while Bluetooth already open.

**Comment by HumanMus1c** [comment]
> Sentry Issue: [ANDROID-G4](https://nearshare.sentry.io/issues/5618334156/?referrer=github_integration)

What's this?

**Comment by ShortDevelopment** [comment]
The internal crash report

**Comment by ShortDevelopment** [comment]
@HumanMus1c Thanks for reporting this (so quickly?!!)
I've confirmed the (small) bug and am working on a fix.
