### ISSUE TITLE
Can't send large files

### ISSUE THREAD

**Issue by WXZhao7** [nearby-sharing/android#93]
Wow, I found a treasure!
I installed the beta version, and everything worked except sending the file larger than ~250Mb. Here is my screen recording.

https://github.com/ShortDevelopment/Nearby-Sharing-Windows/assets/56864878/ef5ab4af-c73e-4703-b735-1d754b8756ad

Another confusing thing is the default receive path. The file stored at `/storage/emulated/0/Android/media/de.shortdev.nearby_sharing_windows/Download/` not friendly for user. I guess this just a beta/test setting:)

**Comment by WXZhao7** [comment]
This version [v1.3.3-beta](https://github.com/ShortDevelopment/Nearby-Sharing-Windows/releases/tag/v1.3.3-beta) not contain this issue.

**Comment by ShortDevelopment** [comment]
That's likely doe to the custom send implementation (#21) I've added in `v1.4.0`.
I'll have a look; Thank you!

**Comment by ShortDevelopment** [comment]
`ReadAsync` might return before reading all bytes!
https://github.com/nearby-sharing/android/blob/8e641fe6773d02290aeffe150ff8105529fa463f/Nearby%20Sharing%20Windows/SendActivity.cs#L166-L167
